// Generated by CoffeeScript 1.10.0
(function() {
  this.Configuration = (function() {
    function Configuration() {
      this.wires = [];
      this.resistors = [];
      this.capacitors = [];
      this.inductors = [];
      this.opamps = [];
    }

    Configuration.prototype.addWire = function(x1, y1, x2, y2) {
      if (!contains(this.wires, [x1, y1, x2, y2])) {
        return this.wires.push([x1, y1, x2, y2]);
      }
    };

    Configuration.prototype.toString = function() {
      return JSON.stringify([]);
    };

    Configuration.prototype.fromString = function(str) {
      var pr;
      pr = JSON.parse(str);
    };

    return Configuration;

  })();

}).call(this);
