// Generated by CoffeeScript 1.10.0
(function() {
  this.DescArea = (function() {
    var instance;

    instance = null;

    function DescArea() {
      var SA, _svg;
      if (instance) {
        return instance;
      } else {
        instance = this;
      }
      SA = window.StatArea();
      this.x = SA.w;
      this.y = 0;
      this.w = $(window).width() - 30 - this.x;
      this.h = $(window).height() - 10;
      _svg = d3.select("body").append("svg").attr("width", this.w).attr("height", this.h).attr("style", "left: " + this.x + " px");
      this.svg = _svg.append("g").attr("width", this.w).attr("height", this.h);
      this.svg.append("rect").attr("x", 0).attr("y", 0).attr("width", this.w).attr("height", this.h).style("fill", "white");
      this.svg.on("mousemove", function(e) {
        var Metastate;
        Metastate = window.Metastate();
        return Metastate.updateGhost(d3.mouse(this)[0], d3.mouse(this)[1]);
      });
      this.svg.on("click", function(e) {
        var Metastate;
        Metastate = window.Metastate();
        switch (Metastate.selected) {
          case Elements.RESISTOR:
          case Elements.CAPACITOR:
          case Elements.INDUCTOR:
          case Elements.OPAMP:
          case Elements.V_IN:
          case Elements.V_OUT:
          case Elements.V_SRC:
            return Metastate.addElement(d3.mouse(this)[0], d3.mouse(this)[1], Metastate.getValue());
        }
      });
    }

    return DescArea;

  })();

}).call(this);
