// Generated by CoffeeScript 1.10.0
(function() {
  this.Drawable = (function() {
    function Drawable() {}

    Drawable.prototype.initialize = function() {};

    Drawable.prototype.redraw = function() {};

    return Drawable;

  })();

}).call(this);
