// Generated by CoffeeScript 1.10.0
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.init = function() {
    var CapacitorSprite, Configuration, DA, Drawable, Elements, Grid, InductorSprite, Metastate, ResistorSprite, SA, Sprite, State, WireGhostSprite, WireSprite;
    if (Meteor.isClient) {
      ({
        contains: function(array, element) {
          var i, j, k, l, ref, ref1;
          for (i = k = 0, ref = array.length; 0 <= ref ? k <= ref : k >= ref; i = 0 <= ref ? ++k : --k) {
            for (j = l = 0, ref1 = element.length; 0 <= ref1 ? l <= ref1 : l >= ref1; j = 0 <= ref1 ? ++l : --l) {
              if (array[i][j] !== element[j]) {
                return false;
              }
            }
            return true;
          }
          return false;
        }
      });
      Elements = window.Elements;
      SA = new window.StatArea();
      DA = new window.DescArea();
      Drawable = window.Drawable;
      Grid = window.Grid;
      Configuration = window.Configuration;
      Metastate = new window.Metastate(new Configuration());
      Sprite = window.Sprite;
      WireSprite = window.WireSprite;
      WireGhostSprite = window.WireGhostSprite;
      ResistorSprite = window.ResistorSprite;
      InductorSprite = window.InductorSprite;
      CapacitorSprite = window.CapacitorSprite;
      State = window.State;
      Grid.initialize();
      return $("body").keydown(function(e) {
        switch (e.keyCode) {
          case 38:
            Grid.zoomIn();
            Grid.redraw();
            return Metastate.updateSVGs();
          case 40:
            Grid.zoomOut();
            Grid.redraw();
            return Metastate.updateSVGs();
          case 82:
            Metastate.selected = Elements.RESISTOR;
            return Metastate.updateGhost();
          case 67:
            Metastate.selected = Elements.CAPACITOR;
            return Metastate.updateGhost();
          case 76:
            Metastate.selected = Elements.INDUCTOR;
            return Metastate.updateGhost();
          case 48:
          case 49:
          case 50:
          case 51:
          case 52:
          case 53:
          case 54:
          case 55:
          case 56:
          case 57:
            DA = window.DescArea();
            Metastate.value_text += "" + (e.keyCode - 48);
            return Metastate.updateGhost();
          case 8:
            e.preventDefault();
            DA = window.DescArea();
            Metastate.value_text = Metastate.value_text.slice(0, -1);
            return Metastate.updateGhost();
        }
      });
    }
  };

}).call(this);
