// Generated by CoffeeScript 1.10.0
(function() {
  var State;

  State = (function() {
    var instance;

    instance = null;

    function State(config) {
      this.config = config;
      if (instance) {
        return instance;
      } else {
        instance = this;
      }
    }

    State.prototype.start = function() {
      return Metastate.updateSVGs();
    };

    return State;

  })();

  this.State = new State();

}).call(this);
