// Generated by CoffeeScript 1.10.0
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  this.WireSprite = (function(superClass) {
    extend(WireSprite, superClass);

    function WireSprite() {
      return WireSprite.__super__.constructor.apply(this, arguments);
    }

    WireSprite.constructSVG = function(x1, y1, x2, y2) {
      var DA, svg, toDStr;
      DA = window.DescArea();
      toDStr = function(lst) {
        return d3.svg.line().x(function(d) {
          return d.x;
        }).y(function(d) {
          return d.y;
        }).interpolate("linear")(lst);
      };
      svg = DA.svg.append("g");
      svg.append("path").attr("d", toDStr([
        {
          "x": x1,
          "y": y1
        }, {
          "x": x2,
          "y": y2
        }
      ])).style("fill", "transparent").attr("stroke", "black").attr("stroke-width", 2);
      svg.append("circle").attr("cx", x1).attr("cy", y1).attr("r", Grid.getTickSize() * .125).style("fill", "black").attr("stroke", "black");
      svg.append("circle").attr("cx", x2).attr("cy", y2).attr("r", Grid.getTickSize() * .125).style("fill", "black").attr("stroke", "black");
      return svg;
    };

    return WireSprite;

  })(Sprite);

}).call(this);
