// Generated by CoffeeScript 1.10.0
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  this.WireGhostSprite = (function(superClass) {
    extend(WireGhostSprite, superClass);

    function WireGhostSprite() {
      return WireGhostSprite.__super__.constructor.apply(this, arguments);
    }

    WireGhostSprite.constructSVG = function(x1, y1, x2, y2) {
      var DA, svg;
      DA = window.DescArea();
      svg = DA.svg.append("g");
      svg.append("circle").attr("cx", x1).attr("cy", y1).attr("r", Grid.getTickSize() * .125).style("fill", "black").attr("stroke", "black");
      return svg;
    };

    return WireGhostSprite;

  })(Sprite);

}).call(this);
